

name = "freshka-worker"
main = "src/index.js"
compatibility_date = "2025-12-11"
account_id = "e109341b4c7a023682abc874f81855c4"
workers_dev = true

# include static assets from public/
[assets]
directory = "./public"

[build]
upload_format = "modules"
