name = "freshka-pages"
compatibility_date = "2025-12-11"
account_id = "e109341b4c7a023682abc874f81855c4"
workers_dev = true

# R2 binding used above (FRESHKA_R2)
[[r2_buckets]]
binding = "FRESHKA_R2"
bucket_name = "freshka-bucket"
preview_bucket_name = "freshka-bucket"
